import Head from "next/head";

type PageProps = {
  pageTitle: string;
};

export default function SEO({ pageTitle }: PageProps) {
  return (
    <Head>
      <title>{pageTitle}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}
